# Generated by Django 3.1.1 on 2021-01-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedynamic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='_', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
