# Generated by Django 3.1.1 on 2021-01-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitedynamic', '0002_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='photo',
            field=models.ImageField(default='_', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
